dist: xenial
sudo: required
git:
  depth: false
language: node_js # npm is needed to install postcss-cli
node_js: "lts/*"
env:
  global:
    - HUGO_RELEASE=0.64.0

install:
  - npm install postcss-cli autoprefixer
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo --environment development
  - hugo --environment production

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $token
  keep-history: true
  local-dir: public
  repo: lim-team/lim-team.github.io
  target-branch: master
  verbose: true
  on:
    branch: master
