git:
  depth: false
  
env:
  matrix:
    - YOUR_ENCRYPTED_VARIABLE

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v0.64.0/hugo_0.64.0_Linux-64bit.tar.gz
  - tar xf hugo_0.64.0_Linux-64bit.tar.gz
  - mv hugo ~/bin/

script:
  - hugo --gc --minify

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $token
  keep-history: true
  local-dir: public
  repo: lim-team/lim-team.github.io
  target-branch: master
  verbose: true
  on:
    branch: master
